In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [53]:
i=cv2.imread('img',0)
m,n=i.shape
i=cv2.threshold(i,127,255,cv2.THRESH_BINARY)[1]
cv2.imshow('img',i)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Gaussian Pyramid

In [31]:
l=cv2.resize(i,(2000,2000))

In [32]:
for j in range(2):
    cv2.imshow(f'img{j}',l)
    l=cv2.pyrDown(l)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
l=cv2.resize(i,(150,150))

In [34]:
for j in range(2):
    cv2.imshow(f'img{j}',l)
    l=cv2.pyrUp(l)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Laplacian Pyramid

In [75]:
l=cv2.resize(i,(150,150))

In [79]:
k=[]
for j in range(3):
    k.append(cv2.pyrUp(l))
    v=cv2.subtract(k[j-1],i)
    cv2.imshow('v',v)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
print(v)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [243 242 241 ... 247 252 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]


In [66]:
import cv2

# Load the image
img = cv2.imread('car.jpg')
lower = img.copy()

# Create a Gaussian Pyramid
gaussian_pyr = [lower]
for i in range(3):
   lower = cv2.pyrDown(lower)
   gaussian_pyr.append(lower)

# Last level of Gaussian remains same in Laplacian
laplacian_top = gaussian_pyr[-1]

# Create a Laplacian Pyramid
laplacian_pyr = [laplacian_top]
for i in range(3,0,-1):
   size = (gaussian_pyr[i - 1].shape[1], gaussian_pyr[i - 1].shape[0])
   gaussian_expanded = cv2.pyrUp(gaussian_pyr[i], dstsize=size)
   laplacian = cv2.subtract(gaussian_pyr[i-1], gaussian_expanded)
   laplacian_pyr.append(laplacian)

# create three windows to display three layers of images
cv2.namedWindow('Layer 1', cv2.WINDOW_AUTOSIZE)
cv2.namedWindow('Layer 2', cv2.WINDOW_AUTOSIZE)
cv2.namedWindow('Layer 3', cv2.WINDOW_AUTOSIZE)

# display all three layers
cv2.imshow('Layer 1',laplacian_pyr[3])
cv2.imshow('Layer 2',laplacian_pyr[2])
cv2.imshow('Layer 3',laplacian_pyr[1])
cv2.waitKey(0)
cv2.destroyAllWindows()

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [244, 243, 242, ..., 248, 253, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)